### ISSUE TITLE
Can't create admin user 

### ISSUE THREAD

**Issue by Alexvianet** [cloudfoundry-community/influxdb-boshrelease#3]
```
instance_groups:
- azs:
  - azs1
  instances: 1
  jobs:
  - name: influxdb
    release: influxdb
  name: influxdb
  networks:
  - name: dynamic
  persistent_disk_type: 50gb
  properties:
    influxdb:
      users:
        - name: foo
          password: bar
          privilege: readwrite
          database: prometheus
        - name: foo
          password: bar
          privilege: readwrite
          database: sampledb
        - name: alex
          password: alex
          privilege: admin
      databases:
        - prometheus
        - sampledb
      retention_policy_rules:
        prometheus:
          default: week
          retention_policies:
            - name:  week
              duration: 14d
  stemcell: trusty
  vm_type: 2cpu_4gbram_20gbdisk
```

recive:
```
# bosh2 -d influxdb deploy influxdb_manifest.yml                                                                                                                       
Using deployment 'influxdb'

  instance_groups:
  - name: influxdb
    properties:
      influxdb:
        users:
+       - name: "<redacted>"
+         password: "<redacted>"
+         privilege: "<redacted>"

Continue? [yN]: y

Task 4249802

Task 4249802 | 09:39:31 | Preparing deployment: Preparing deployment (00:00:00)
Task 4249802 | 09:39:32 | Error: Unable to render instance groups for deployment. Errors are:
  - Unable to render jobs for instance group 'influxdb'. Errors are:
    - Unable to render templates for job 'influxdb'. Errors are:
      - Error filling in template 'influxdb_setup.erb' (line 54: Admin privileges for user alex can't be applied to a single database)
```

i have comment:
#  raise "Admin privileges for user #{user['name']} can't be applied to a single database" if user['privilege'] == 'admin' && user['database'] != ''

and now i get:
```
Continue? [yN]: y

Task 4249896

Task 4249896 | 09:43:16 | Preparing deployment: Preparing deployment (00:00:00)
Task 4249896 | 09:43:16 | Error: Unable to render instance groups for deployment. Errors are:
  - Unable to render jobs for instance group 'influxdb'. Errors are:
    - Unable to render templates for job 'influxdb'. Errors are:
      - Error filling in template 'influxdb_setup.erb' (line 57: Database name () is not listed in influxdb.databases)  
```
